# Define the stages of the pipeline
stages:
  - init
  - setup
  - build
  - lint
  - test
  - security
  - package
  - deploy
  - notify
  - cleanup

# Step 1: Initialization
init:
  stage: init
  script:
    - echo "Initializing the pipeline..."

# Step 2: Setup Environment
setup:
  stage: setup
  script:
    - echo "Setting up environment..."
  dependencies:
    - init

# Step 3: Build
build:
  stage: build
  script:
    - echo "Building the project..."
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
  dependencies:
    - setup

# Step 4: Linting
lint:
  stage: lint
  script:
    - echo "Linting the code..."
  dependencies:
    - build

# Step 5: Testing
test:
  stage: test
  script:
    - echo "Running tests..."
  dependencies:
    - build
    - lint

# Step 6: Security Checks
security:
  stage: security
  script:
    - echo "Performing security checks..."
  dependencies:
    - build
    - test

# Step 7: Package
package:
  stage: package
  script:
    - echo "Packaging the project..."
  dependencies:
    - build
    - test
    - security

# Step 8: Deploy
deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
  only:
    - master
  dependencies:
    - package

# Step 9: Notify
notify:
  stage: notify
  script:
    - echo "Sending notifications..."
  dependencies:
    - deploy

# Step 10: Cleanup
cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up..."
  dependencies:
    - notify
